[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  NODE_VERSION = "14.15.0"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
[template.environment]
  GATSBY_SPOTIFY_CLIENT_ID = "This is your Spotify Client ID"
  GATSBY_SPOTIFY_CLIENT_SECRET = "This is your Spotify Client Secret"

