backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "song"
    label: "Songs"
    folder: "src/pages/song"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "song",
        }
      - { label: "Song Name", name: "song", widget: "string" }
      - { label: "Spotify URL", name: "url", widget: "string" }
      - { label: "Song File", name: "file", widget: "file" }

  - name: "settings"
    label: "Site Settings"
    files:
      - file: "src/pages/index.md"
        label: "Site Settings"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: "Artist Name", name: "title", widget: "string" }
          - { label: "Artist Description", name: "subtitle", widget: "string" }
          - { label: "Artist Image", name: "image", widget: "image" }
          - { label: "Color Palette", name: "color", widget: "color" }
          - { label: "Tags", name: "select", widget: "list", multiple: true, default: ["Songwriter", "Guitarist", "Singer", "Bassist", ] }